version: '3'

vars:
  CERTS_DIR: "certs"
  ZITADEL_PRIVATE_KEY: "certs/331462024888320002.json"
  ZITADEL_DOMAIN: "http://localhost:8080"
  
tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  generate-webhookserver-certs:
    desc: Generate all certificates for webhook server
    cmds:
      - mkdir -p "{{.CERTS_DIR}}" && openssl req -x509 -nodes -newkey rsa:4096 -keyout "{{.CERTS_DIR}}/server.key" -out "{{.CERTS_DIR}}/server.crt" -days 1024 -subj "/CN=webhook.zitadel.svc" -sha256

  lint-ci:
    desc: Run golangci-lint using Docker (matches CI environment)
    cmds:
      - |
        GOLANGCI_VERSION=$(cat .golangci-version)
        docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:${GOLANGCI_VERSION} golangci-lint run -v

  run-webhookserver:
    desc: Run the user authentication webhook server locally
    deps:
      - generate-webhookserver-certs
    cmds:
      - |
          go run cmd/main.go authn-webhook \
            --webhook-port 8443 \
            --cert-dir "certs" \
            --cert-file "server.crt" \
            --key-file "server.key" \
            --zitadel-private-key "{{.ZITADEL_PRIVATE_KEY}}" \
            --zitadel-domain "{{.ZITADEL_DOMAIN}}" \
            --jwt-expiration 1h \
            --metrics-bind-address :8081
            
  run-actionsserver:
    desc: Run the HTTP actions server locally
    deps:
      - generate-webhookserver-certs
    cmds:
      - |
          go run cmd/main.go actions-server \
            --addr :8443 \
            --kubeconfig ~/.kube/config \
            --disable-signature-validation=true
  

