---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - iam.miloapis.com
  resources:
  - machineaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - iam.miloapis.com
  resources:
  - machineaccounts/finalizers
  verbs:
  - update
- apiGroups:
  - iam.miloapis.com
  resources:
  - machineaccounts/status
  verbs:
  - get
  - patch
  - update
