apiVersion: v1
kind: Service
metadata:
  name: authn-webhook
  labels:
    app.kubernetes.io/name: authn-webhook
    app.kubernetes.io/part-of: auth-provider-zitadel
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    app.kubernetes.io/name: authn-webhook
    app.kubernetes.io/part-of: auth-provider-zitadel
  ports:
    - name: webhook-https
      port: 8090
      targetPort: 8090
      protocol: TCP
    - name: metrics
      port: 8443
      targetPort: 8443
      protocol: TCP