apiVersion: apps/v1
kind: Deployment
metadata:
  name: authn-webhook
  labels:
    app.kubernetes.io/name: authn-webhook
    app.kubernetes.io/part-of: auth-provider-zitadel
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: authn-webhook
      app.kubernetes.io/part-of: auth-provider-zitadel
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: authn-webhook
        app.kubernetes.io/part-of: auth-provider-zitadel
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: authn-webhook
          image: auth-provider-zitadel:latest
          imagePullPolicy: IfNotPresent
          args:
            - authn-webhook
            - --webhook-port=8090
            - --cert-dir=certs
            - --cert-file=tls.crt
            - --key-file=tls.key
            - --zitadel-domain=$(ZITADEL_DOMAIN)
            - --jwt-expiration=1h
            - --metrics-bind-address=:8443
          env:
            - name: ZITADEL_DOMAIN
              value: https://auth.datum.net
          ports:
            - containerPort: 8443
              name: metrics
              protocol: TCP
            - containerPort: 8090
              name: webhook
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - "ALL"
          volumeMounts: []
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi

      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
      volumes: []