apiVersion: v1
kind: Service
metadata:
  name: zitadel-proxy
  namespace: zitadel-system
spec:
  selector:
    app.kubernetes.io/name: zitadel
    app.kubernetes.io/instance: zitadel
    app.kubernetes.io/component: start
  ports:
    - port: 443
      targetPort: 9443
      protocol: TCP
